# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4cf2c83e2dd998de7343beaab57f1a59dfedab6fdf3661c15d7a944bae22a5c227a6b222c124218f2eff702bee24fea5811bcfb43941d28ad12d15fc51e9aa5

test:
  secret_key_base: 32cc01916a619efd0d8352e63dfef427d7a2c306fcf5d251965519564b87e32bc9f096cc6201026dc9f72b10db8e36c4adcd4fe6342e0ad7919c7f0c22970af3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
